version: '3'
services:
  api:
    image: cameratraps-batch-api:local
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - LISTEN_PORT=8080
      - FLASK_ENV=development
      - FLASK_APP=server